### ISSUE TITLE
add "gather all" option

### ISSUE THREAD

**Issue by theHankTaylor** [nicolewhite/same-domain-tabs#1]
Add a "gather all" button to gather all tabs of similar domain everywhere, regardless of the tab currently selected.

**Comment by nicolewhite** [comment]
i added this in v0.0.2 which i just published to the chrome store. idk when chrome forces you to update your extensions but you can update manually under chrome://extensions by checking developer mode and clicking 'update extensions now'

**Comment by theHankTaylor** [comment]
tried it, working well 👍
